spring:
  shardingsphere:
    props:
      sql-show: true
    datasource:
      names: write-ds,read-ds-0,read-ds-1
      write-ds:
        jdbc-url: jdbc:mysql://40.73.16.169:3306/sharding-db0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Admin@12345678
      read-ds-0:
        jdbc-url: jdbc:mysql://40.73.16.169:3306/sharding-db1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Admin@12345678
      read-ds-1:
        jdbc-url: jdbc:mysql://40.73.16.169:3306/sharding-db0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Admin@12345678
    rules:
      readwrite-splitting:
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
        data-sources:
          pr_ds:
            write-data-source-name: write-ds
            read-data-source-names: read-ds-0,read-ds-1
            load-balancer-name: round_robin